version: "2"

services:
  bastion:
     hostname: bastion
     image: wiwwo:pgplaygrd
     ports:
         - "22:22"
     environment:
         - WHAT_AM_I=bastion
     networks:
         - bridge-docker

  pg_red:
     hostname: pg_red
     image: wiwwo:pgplaygrd
     ports:
         - "5445:5432"
     environment:
         - WHAT_AM_I=primary
     networks:
         - bridge-docker

  pg_green:
     hostname: pg_green
     image: wiwwo:pgplaygrd
     depends_on:
         - pg_red
     ports:
         - "5446:5432"
     environment:
         - WHAT_AM_I=secondary
         - NEW_PRIMARY=pg_red
     networks:
         - bridge-docker
     restart: always

  pg_blue:
     hostname: pg_blue
     image: wiwwo:pgplaygrd
     depends_on:
         - pg_red
     ports:
         - "5447:5432"
     environment:
         - WHAT_AM_I=secondary
         - NEW_PRIMARY=pg_red
     networks:
         - bridge-docker
     restart: always

networks:
  bridge-docker:
